from . import auth_routes
from . import farm_routes
from . import score_routes
from . import notification_routes
from . import mission_routes
from . import proof_routes
from . import social_routes
from . import leaderboard_routes
from . import grc_routes
from . import ai_routes
from . import marketplace_routes
from . import reward_routes
from . import admin_routes
